{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "e9853a72",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>checking_balance</th>\n",
       "      <th>months_loan_duration</th>\n",
       "      <th>credit_history</th>\n",
       "      <th>purpose</th>\n",
       "      <th>amount</th>\n",
       "      <th>savings_balance</th>\n",
       "      <th>employment_length</th>\n",
       "      <th>installment_rate</th>\n",
       "      <th>personal_status</th>\n",
       "      <th>other_debtors</th>\n",
       "      <th>...</th>\n",
       "      <th>property</th>\n",
       "      <th>age</th>\n",
       "      <th>installment_plan</th>\n",
       "      <th>housing</th>\n",
       "      <th>existing_credits</th>\n",
       "      <th>default</th>\n",
       "      <th>dependents</th>\n",
       "      <th>telephone</th>\n",
       "      <th>foreign_worker</th>\n",
       "      <th>job</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1169</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>67</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>48</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>5951</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>22</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0</td>\n",
       "      <td>12</td>\n",
       "      <td>0</td>\n",
       "      <td>5</td>\n",
       "      <td>2096</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>49</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1</td>\n",
       "      <td>42</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>7882</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>...</td>\n",
       "      <td>1</td>\n",
       "      <td>45</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1</td>\n",
       "      <td>24</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>4870</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>53</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>995</th>\n",
       "      <td>0</td>\n",
       "      <td>12</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>1736</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>31</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>996</th>\n",
       "      <td>1</td>\n",
       "      <td>30</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>3857</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>1</td>\n",
       "      <td>40</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>997</th>\n",
       "      <td>0</td>\n",
       "      <td>12</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>804</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>3</td>\n",
       "      <td>38</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>998</th>\n",
       "      <td>1</td>\n",
       "      <td>45</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1845</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>23</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>999</th>\n",
       "      <td>2</td>\n",
       "      <td>45</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>4576</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>3</td>\n",
       "      <td>27</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1000 rows × 21 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     checking_balance  months_loan_duration  credit_history  purpose  amount  \\\n",
       "0                   1                     6               0        0    1169   \n",
       "1                   2                    48               1        0    5951   \n",
       "2                   0                    12               0        5    2096   \n",
       "3                   1                    42               1        2    7882   \n",
       "4                   1                    24               2        1    4870   \n",
       "..                ...                   ...             ...      ...     ...   \n",
       "995                 0                    12               1        2    1736   \n",
       "996                 1                    30               1        3    3857   \n",
       "997                 0                    12               1        0     804   \n",
       "998                 1                    45               1        0    1845   \n",
       "999                 2                    45               0        3    4576   \n",
       "\n",
       "     savings_balance  employment_length  installment_rate  personal_status  \\\n",
       "0                  1                  1                 4                0   \n",
       "1                  0                  0                 2                1   \n",
       "2                  0                  2                 2                0   \n",
       "3                  0                  2                 2                0   \n",
       "4                  0                  0                 3                0   \n",
       "..               ...                ...               ...              ...   \n",
       "995                0                  2                 3                1   \n",
       "996                0                  0                 4                3   \n",
       "997                0                  1                 4                0   \n",
       "998                0                  0                 4                0   \n",
       "999                2                  4                 3                0   \n",
       "\n",
       "     other_debtors  ...  property  age  installment_plan  housing  \\\n",
       "0                0  ...         0   67                 0        0   \n",
       "1                0  ...         0   22                 0        0   \n",
       "2                0  ...         0   49                 0        0   \n",
       "3                1  ...         1   45                 0        2   \n",
       "4                0  ...         2   53                 0        2   \n",
       "..             ...  ...       ...  ...               ...      ...   \n",
       "995              0  ...         0   31                 0        0   \n",
       "996              0  ...         1   40                 0        0   \n",
       "997              0  ...         3   38                 0        0   \n",
       "998              0  ...         2   23                 0        2   \n",
       "999              0  ...         3   27                 0        0   \n",
       "\n",
       "     existing_credits  default  dependents  telephone  foreign_worker  job  \n",
       "0                   2        1           1          1               1    0  \n",
       "1                   1        2           1          0               1    0  \n",
       "2                   1        1           2          0               1    1  \n",
       "3                   1        1           2          0               1    0  \n",
       "4                   2        2           2          0               1    0  \n",
       "..                ...      ...         ...        ...             ...  ...  \n",
       "995                 1        1           1          0               1    1  \n",
       "996                 1        1           1          1               1    2  \n",
       "997                 1        1           1          0               1    0  \n",
       "998                 1        2           1          1               1    0  \n",
       "999                 1        1           1          0               1    0  \n",
       "\n",
       "[1000 rows x 21 columns]"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "cr= pd.read_excel(\"credit.xlsx\")\n",
    "cr[\"credit_history\"].replace(['critical','repaid','delayed','fully repaid this bank','fully repaid'],[0,1,2,3,4],inplace=True)\n",
    "cr['checking_balance'].replace(['unknown','< 0 DM','1 - 200 DM','> 200 DM'],[0,1,2,3],inplace=True)\n",
    "cr['purpose'].replace(['radio/tv','car (new)','furniture','car (used)','business','education','repairs','domestic appliances','retraining','others'],[0,1,2,3,4,5,6,7,8,9],inplace=True)\n",
    "cr['savings_balance'].replace(['< 100 DM','unknown','101 - 500 DM','501 - 1000 DM','> 1000 DM'],[0,1,2,3,4],inplace=True)\n",
    "cr['employment_length'].replace(['1 - 4 yrs','> 7 yrs','4 - 7 yrs','0 - 1 yrs','unemployed'],[0,1,2,3,4],inplace=True)\n",
    "cr['personal_status'].replace(['single male','female','married male','divorced male'],[0,1,2,3],inplace=True)\n",
    "cr['other_debtors'].replace(['none','guarantor','co-applicant'],[0,1,2],inplace=True)\n",
    "cr['property'].replace(['real estate','building society savings','unknown/none','other'],[0,1,2,3],inplace=True)\n",
    "cr['installment_plan'].replace(['none','bank','stores'],[0,1,2],inplace=True)\n",
    "cr['housing'].replace(['own','rent','for free'],[0,1,2],inplace=True)\n",
    "cr['telephone'].replace(['none','yes'],[0,1],inplace=True)\n",
    "cr['foreign_worker'].replace(['no','yes'],[0,1],inplace=True)\n",
    "cr['job'].replace(['skilled employee','unskilled resident','mangement self-employed','unemployed non-resident'],[0,1,2,3],inplace=True)\n",
    "cr.drop('Credit-historynum',inplace=True,axis=1)\n",
    "cr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "cfa78411",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "skilled employee           630\n",
       "unskilled resident         200\n",
       "mangement self-employed    148\n",
       "unemployed non-resident     22\n",
       "Name: job, dtype: int64"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cr['job'].value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "8f58fb7e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 1000 entries, 0 to 999\n",
      "Data columns (total 21 columns):\n",
      " #   Column                Non-Null Count  Dtype\n",
      "---  ------                --------------  -----\n",
      " 0   checking_balance      1000 non-null   int64\n",
      " 1   months_loan_duration  1000 non-null   int64\n",
      " 2   credit_history        1000 non-null   int64\n",
      " 3   purpose               1000 non-null   int64\n",
      " 4   amount                1000 non-null   int64\n",
      " 5   savings_balance       1000 non-null   int64\n",
      " 6   employment_length     1000 non-null   int64\n",
      " 7   installment_rate      1000 non-null   int64\n",
      " 8   personal_status       1000 non-null   int64\n",
      " 9   other_debtors         1000 non-null   int64\n",
      " 10  residence_history     1000 non-null   int64\n",
      " 11  property              1000 non-null   int64\n",
      " 12  age                   1000 non-null   int64\n",
      " 13  installment_plan      1000 non-null   int64\n",
      " 14  housing               1000 non-null   int64\n",
      " 15  existing_credits      1000 non-null   int64\n",
      " 16  default               1000 non-null   int64\n",
      " 17  dependents            1000 non-null   int64\n",
      " 18  telephone             1000 non-null   int64\n",
      " 19  foreign_worker        1000 non-null   int64\n",
      " 20  job                   1000 non-null   int64\n",
      "dtypes: int64(21)\n",
      "memory usage: 164.2 KB\n"
     ]
    }
   ],
   "source": [
    "cr.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a4f6b9e5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
